language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t coleplx/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true coleplx/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-684820535781"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY